version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] "
      prefix: "[github-actions] "
    labels:
      - "github-actions"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[npm] "
      prefix: "[npm] "
    labels:
      - "npm"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "main"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[composer] "
      prefix: "[composer] "
    labels:
      - "composer"
